name: GitHub Classroom Workflow

on: 
  push:
    branches:
    - main
    - master

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  autograde:
    # XXX Name should be "Autograding"; GitHub Classroom seems to depend on this!
    name: Autograding
    if: "!contains(github.event.head_commit.message, '[noci]')"
    runs-on: ubuntu-latest
    concurrency:
      group: autograde  # Disallow concurrent autograde job runs
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5 
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt  # TODO? Condition on non-empty (w/ cache above)?
      - uses: clusterhack/github-autograde@v2
      - if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: autograde
          path: ${{ github.workspace }}/autograde.json
          if-no-files-found: ignore
          retention-days: 30
